spring.application.name=api

# URL do banco
spring.datasource.url=jdbc:postgresql://localhost:5432/SEU_BD

# Usuário e senha
spring.datasource.username=SEU_USUÁRIO
spring.datasource.password=SUA_SENHA

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true